server:
  port: 8080

spring:
  profiles:
    active: default
    include:
      - database
      - security
      - document
      - cloud
    google:
      cloud:
        storage:
          bucketName: meta-shop